### ISSUE TITLE
рассмотреть вариант размещения параметров и временных таблиц на главном экране

### ISSUE THREAD

**Issue by LevkinSergey** [hal9000cc/RequestConsole9000#6]
Предложили в чате по универсальным инструментам. 

![image](https://user-images.githubusercontent.com/36307272/84884361-4bb7a480-b09a-11ea-9f47-d39024aa5317.png)

**Comment by LevkinSergey** [comment]
готов подключиться к разработке консоли, т.к. планирую ее включить в универсальные инструменты.

На мой взгляд консоль очень перспективная

**Comment by hal9000cc** [comment]
Приветствую! В принципе, я за любой кипишь, кроме тех принципов, которые изложены в первой статье. В частности, таблицу результата нельзя по ширине резать (как в консоли запросов на скрине). Ширины результата всегда мало.А вот вверху, на мой взгляд, место есть. Текст запроса довольно узкий. Дерево запросов тоже. Опции давно пора в отдельную форму вынести, это на скорую руку было сделано. -- С уважением,Александр Кузнецовhal@hal9000.cc    17.06.2020, 12:59, "Левкин Сергей" <notifications@github.com>: Предложили в чате по универсальным инструментам.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hal9000cc** [comment]
Спасибо!Я только за. -- С уважением,Александр Кузнецовhal@hal9000.cc    17.06.2020, 13:08, "Левкин Сергей" <notifications@github.com>: готов подключиться к разработке консоли, т.к. планирую ее включить в универсальные инструменты.На мой взгляд консоль очень перспективная—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hal9000cc** [comment]
> готов подключиться к разработке консоли, т.к. планирую ее включить в универсальные инструменты. https://github.com/cpr1c/tools_ui_1c
> 
> На мой взгляд консоль очень перспективная

Спасибо! Я только за.

**Comment by hal9000cc** [comment]
Вот если как скрываемое по кнопке окно...
А с другой стороны - какая цель окна временных таблиц? Что это дает пользователю? Увидеть их список? Но и сейчас можно, нажав на кнопку выбора таблицы...

**Comment by LevkinSergey** [comment]
> Вот если как скрываемое по кнопке окно...
или в настройку, которая будет определять местоположение таблиц. Сделать два варианта и в настройки выбор вынести. Но тут не факт что кто-то будет этим пользоваться.

> А с другой стороны - какая цель окна временных таблиц? Что это дает пользователю? Увидеть их список? Но и сейчас можно, нажав на кнопку выбора таблицы...

быстрее просмотреть можно. Тупо меньше кликов. Конечно как в консоли из ИР сделано (дерево запроса) - по опыту очень удобно

> Разместить дополнительную информацию? (время выполнения и др.)

Это было бы очень информативно

> Не понятно, как это сделать без ущерба таблице результата.

я бы сделал свертываемые таблицы. Или кнопка переключатель в шапке- показывать непоказывать

**Comment by LevkinSergey** [comment]
это еще один вариант компоновки. Результаты временных таблицы выводятся кнопками с названием и временем выполнения. Видимость дерева запросов, таблицы параметров и самого текста запроса переключается кнопками на панели вверху. 

![image](https://user-images.githubusercontent.com/36307272/84898961-b4118080-b0b0-11ea-89ef-3f569c3fa4b9.png)

**Comment by hal9000cc** [comment]
> я бы сделал свертываемые таблицы. Или кнопка переключатель в шапке- показывать непоказывать
Да. Мне кажется, так было бы удобнее всего. Как в "инструментах разработчика" сделан эксплорер записи. Открывается в выдвигаемом по кнопке окошке.

То есть, исходное состояние: как сейчас, но слева кнопка, и выпадающий список выбора таблицы перенесен к ней. Пользуемся как сейчас, выбирая таблицу из списка.

При нажатии на кнопку: Слева выдвигается окно с временными таблицами, выпадающий список выбора таблиц скрывается (ибо дубль).

**Comment by LevkinSergey** [comment]
единственное я бы сделал запоминание последнего использованного формата для пользователя

**Comment by hal9000cc** [comment]
Как то так:
![image](https://user-images.githubusercontent.com/46416329/84901239-da84eb00-b0b3-11ea-9c1d-0e5330c58c78.png)

> единственное я бы сделал запоминание последнего использованного формата для пользователя

Да, эргономика - наше все)

**Comment by hal9000cc** [comment]
![image](https://user-images.githubusercontent.com/46416329/84902222-313ef480-b0b5-11ea-8be1-3b09cf4795b5.png)

Тоже выдвигать по кнопке. Эргономика не нарушается, даже если их скрывать. Сейчас: нажатие, что бы открыть вкладку, нажатие, что бы вернуться - 2. Получиться: нажатие - выдвинуть, нажатие - задвинуть - 2.

**Comment by LevkinSergey** [comment]
С параметрами соглсен. 

Есть планы разработку перевести в EDT? Я как туда пересел в конфигуратор крайне неохотно захожу, хотя он в некоторых вещах еще лучше

**Comment by hal9000cc** [comment]
Есть, и даже поставил. Но пока не разбирался..

**Comment by hal9000cc** [comment]
Временные таблицы добавил.

**Comment by hal9000cc** [comment]
Добавил возможность отображения параметров рядом с текстом запроса.
